// Output Variables/Values definition file

// Network Outputs
// None needed so far


// Airflow RDS Output
output "id" {
  value       = aws_db_instance.postgresql.id
  description = "The database instance ID"
}

output "rds_password" {
  value       = aws_db_instance.postgresql.password
  description = "The password set at provision time,~> ALTER USER WITH ENCRYPTED PASSWORD '<new>'; after provision time"
}
//
//output "database_security_group_id" {
//  value       = aws_security_group.postgresql
//  description = "Security group ID of the database"
//}
//
//output "hosted_zone_id" {
//  value       = aws_db_instance.postgresql_rds.hosted_zone_id
//  description = "The zone ID for the autogenerated DNS name given in endpoint"
//}
//
output "hostname" {
  value       = aws_db_instance.postgresql.address
  description = "Public DNS name of database instance"
}
//
output "port" {
  value       = aws_db_instance.postgresql.port
  description = "Port of database instance"
}
//
output "endpoint" {
  value       = aws_db_instance.postgresql.endpoint
  description = "Public DNS name and port separated by a colon"
}

output "alb_public_dns" {
  description = "Goto:"
  value = "https://${aws_alb.airflow.dns_name}"
}

output "redis_endpoint" {
  value       = aws_elasticache_cluster.redis.cluster_address
  description = "Public DNS name and port separated by a colon"
}